srun: Job 1124578 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=1124578.48
2024-03-17 15:28:17.238083: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:17.238082: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:17.238080: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:17.238077: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:17.238204: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:17.238213: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:17.238242: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:17.239296: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:27.332252: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:27.332428: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:27.332492 3122347 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14634d9e7b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14634d9e7be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14634d9e7b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14634d9e7be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


2024-03-17 15:28:27.332688: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:27.332789: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:27.332843 3122348 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15049595fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15049595fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15049595fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15049595fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


2024-03-17 15:28:27.333290: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:27.333402: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:27.333462 3122350 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x153feff93b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x153feff93be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x153feff93b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x153feff93be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


2024-03-17 15:28:27.333567: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:27.333780: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:27.333924 3122349 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15437d043b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15437d043be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15437d043b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15437d043be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


2024-03-17 15:28:27.344454: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:27.344697: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:27.344801  899020 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15065a837b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15065a837be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15065a837b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15065a837be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


2024-03-17 15:28:27.345724: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:27.345839: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:27.345891  899021 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a4d39abb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a4d39abbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a4d39abb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a4d39abbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


2024-03-17 15:28:27.346053: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:27.346166: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:27.346228  899018 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x1495d6263b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x1495d6263be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x1495d6263b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x1495d6263be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


2024-03-17 15:28:27.346318: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:27.346420: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:27.346481  899019 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14bd7de5fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14bd7de5fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14bd7de5fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14bd7de5fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x153feff93b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x153feff93be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x153feff93b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x153feff93be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14634d9e7b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14634d9e7be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14634d9e7b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14634d9e7be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15049595fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15049595fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15049595fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15049595fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15437d043b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15437d043be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15437d043b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15437d043be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15065a837b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15065a837be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x15065a837b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x15065a837be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a4d39abb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a4d39abbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a4d39abb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a4d39abbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x1495d6263b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x1495d6263be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x1495d6263b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x1495d6263be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14bd7de5fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14bd7de5fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14bd7de5fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14bd7de5fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[1024,512,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[1024,512,2048]
		==========================


*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3122349] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:899020] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:899019] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:899018] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3122350] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3122347] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3122348] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:899021] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: error: r7i6n7: tasks 5,7: Exited with exit code 1
srun: Terminating StepId=1124578.48
srun: error: r7i1n0: tasks 1,3: Exited with exit code 1
slurmstepd: error: *** STEP 1124578.48 ON r7i1n0 CANCELLED AT 2024-03-17T15:28:28 ***
srun: error: r7i6n7: task 6: Exited with exit code 1
srun: error: r7i1n0: task 2: Exited with exit code 1
srun: error: r7i6n7: task 4: Exited with exit code 1
srun: error: r7i1n0: task 0: Exited with exit code 1
