2024-03-17 15:28:33.933418: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:33.934156: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:33.934163: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:33.934295: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:33.934516: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:33.933425: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:33.933417: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:33.933417: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:28:44.015701: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:44.015859: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
2024-03-17 15:28:44.015921: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
E0317 15:28:44.015919  899492 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14cd07b1bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14cd07b1bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14cd07b1bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14cd07b1bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


2024-03-17 15:28:44.016020: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:44.016074  899491 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x147811b6fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x147811b6fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x147811b6fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x147811b6fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


2024-03-17 15:28:44.017091: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:44.017258: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:44.017330  899489 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14e399053b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14e399053be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14e399053b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14e399053be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


2024-03-17 15:28:44.017388: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:44.017498: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:44.017567  899490 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14f6a7ac7b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14f6a7ac7be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14f6a7ac7b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14f6a7ac7be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


2024-03-17 15:28:44.027112: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:44.027338: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:44.027448 3122864 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x154763347b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x154763347be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x154763347b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x154763347be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


2024-03-17 15:28:44.027556: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:44.027653: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:44.027713 3122865 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x149accb8fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x149accb8fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x149accb8fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x149accb8fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


2024-03-17 15:28:44.028187: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:44.028301: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:44.028354 3122867 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x151a90c07b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x151a90c07be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x151a90c07b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x151a90c07be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


2024-03-17 15:28:44.029225: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:28:44.029338: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:28:44.029390 3122866 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x147c96fbbb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x147c96fbbbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x147c96fbbb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x147c96fbbbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14cd07b1bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14cd07b1bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14cd07b1bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14cd07b1bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x147811b6fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x147811b6fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x147811b6fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x147811b6fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14f6a7ac7b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14f6a7ac7be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14f6a7ac7b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14f6a7ac7be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14e399053b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14e399053be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14e399053b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14e399053be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x154763347b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x154763347be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x154763347b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x154763347be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x149accb8fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x149accb8fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x149accb8fb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x149accb8fbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x151a90c07b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x151a90c07be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x151a90c07b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x151a90c07be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x147c96fbbb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x147c96fbbbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x147c96fbbb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x147c96fbbbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[512,1024,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[512,1024,2048]
		==========================


*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3122864] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:899489] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:899492] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3122866] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:899490] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3122865] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3122867] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:899491] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: error: r7i6n7: tasks 5,7: Exited with exit code 1
srun: Terminating StepId=1124578.49
slurmstepd: error: *** STEP 1124578.49 ON r7i1n0 CANCELLED AT 2024-03-17T15:28:44 ***
srun: error: r7i1n0: tasks 1,3: Exited with exit code 1
srun: error: r7i6n7: task 6: Exited with exit code 1
srun: error: r7i1n0: task 2: Exited with exit code 1
srun: error: r7i6n7: task 4: Exited with exit code 1
srun: error: r7i1n0: task 0: Exited with exit code 1
