2024-03-17 15:29:06.187592: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:29:06.187903: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:29:06.187903: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:29:06.187941: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:29:06.187929: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:29:06.187592: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:29:06.187729: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:29:06.187852: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 11.21GiB (12041271705 bytes) by rematerialization; only reduced to 32.00GiB (34359738368 bytes), down from 32.00GiB (34359738368 bytes) originally
2024-03-17 15:29:16.271752: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:29:16.271780: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:29:16.271865: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
2024-03-17 15:29:16.271887: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:29:16.271924  900438 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14814a97bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14814a97bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14814a97bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14814a97bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


2024-03-17 15:29:16.277031: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
E0317 15:29:16.271942  900439 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
2024-03-17 15:29:16.277146: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14618c747b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14618c747be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
E0317 15:29:16.277218 3123895 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14618c747b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14618c747be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14f10df1bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14f10df1bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
2024-03-17 15:29:16.272392: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14f10df1bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14f10df1bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


2024-03-17 15:29:16.272457: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:29:16.277360: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:29:16.272609: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
2024-03-17 15:29:16.277588: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
2024-03-17 15:29:16.272677: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:29:16.277743 3123894 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
E0317 15:29:16.272704  900440 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14d22d517b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14d22d517be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a2a8c87b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a2a8c87be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14d22d517b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14d22d517be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a2a8c87b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a2a8c87be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


2024-03-17 15:29:16.277904: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
E0317 15:29:16.272790  900441 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
2024-03-17 15:29:16.278145: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x154edfd97b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x154edfd97be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
E0317 15:29:16.278253 3123897 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x154edfd97b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x154edfd97be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14e47a243b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14e47a243be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14e47a243b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14e47a243be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


2024-03-17 15:29:16.278365: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869184)requested by op 
2024-03-17 15:29:16.278467: W external/tsl/tsl/framework/bfc_allocator.cc:494] ***************************************************_________________________________________________
E0317 15:29:16.278532 3123896 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a671d63b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a671d63be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a671d63b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a671d63be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14618c747b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14618c747be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14618c747b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14618c747be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x154edfd97b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x154edfd97be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x154edfd97b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x154edfd97be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a2a8c87b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a2a8c87be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a2a8c87b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a2a8c87be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14814a97bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14814a97bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14814a97bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14814a97bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14f10df1bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14f10df1bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14f10df1bb50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14f10df1bbe0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14e47a243b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14e47a243be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14e47a243b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14e47a243be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14d22d517b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14d22d517be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14d22d517b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14d22d517be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 168, in <module>
    run_benchmark(pdims, global_shape, backend, nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/pfft3d.py", line 93, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869184 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:    8.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   28.00GiB
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a671d63b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a671d63be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: s8[17179869184]
		==========================

	Buffer 2:
		Size: 8.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(_do_pfft)/custom_partitioning[partition=<function partition at 0x14a671d63b50> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands at 0x14a671d63be0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[<FftType.FFT: 0>, False]]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/venv/v100/lib/python3.10/site-packages/jaxdecomp/_src/fft.py" source_line=307
		XLA Label: fusion
		Shape: c64[256,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================


*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3123894] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3123896] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:900441] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:900440] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:900439] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3123897] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i6n7:900438] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[r7i1n0:3123895] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: error: r7i6n7: tasks 5,7: Exited with exit code 1
srun: Terminating StepId=1124578.51
slurmstepd: error: *** STEP 1124578.51 ON r7i1n0 CANCELLED AT 2024-03-17T15:29:16 ***
srun: error: r7i1n0: tasks 1,3: Exited with exit code 1
srun: error: r7i6n7: task 6: Exited with exit code 1
srun: error: r7i1n0: task 2: Exited with exit code 1
srun: error: r7i6n7: task 4: Exited with exit code 1
srun: error: r7i1n0: task 0: Exited with exit code 1
